name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Tarif EDF release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v1
      - name: "Set version number"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/isapi_door/manifest.json"
      # Pack the HACS dir as a zip and upload to the release
      - name: ZIP Dir
        run: |
          cd "${{ github.workspace }}/custom_components/isapi_door"
          zip hikvision_isapi_door.zip -r ./
      - name: Upload zip to release
        uses: softprops/action-gh-release@v3.0.2
        with:
          files: ${{ github.workspace }}/custom_components/isapi_door/hikvision_isapi_door.zip